name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Node meta
        id: docker_meta_node
        uses: docker/metadata-action@v3
        with:
          images: pastvu/node
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push node
        id: docker_build_node
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            NODE_TAG=${{ steps.docker_meta_node.outputs.tags }}
          tags: ${{ steps.docker_meta_node.outputs.tags }}
          labels: ${{ steps.docker_meta_node.outputs.labels }}
          push: true

      - name: Image digest
        run: |
          echo ${{ steps.docker_build_node.outputs.digest }}
