name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  workflow_dispatch:


jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: pastvu/node
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push node
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            NODE_TAG=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.version'] }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: ${{ startsWith(github.ref, 'refs/tags/v') }} # Push on tags only.

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.digest }}
